name: 'nyc_traffic'
version: '1.0.0'
config-version: 2

profile: 'nyc_traffic'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  nyc_traffic:
    # Materialize everything as tables for simplicity
    materialized: table